#!/bin/bash
# =============================================================================
# RC Racer Development Environment Setup
# =============================================================================
# This script sets up everything a new developer needs to start working on
# the RC Racer project using Docker.
#
# Usage:
#   ./scripts/setup-dev-env.sh
#
# What it does:
#   1. Checks for required tools (Docker, Docker Compose)
#   2. Configures X11 forwarding for GUI apps (Gazebo, RViz)
#   3. Creates docker/.env from template
#   4. Builds the development container
#   5. Verifies the setup
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# -----------------------------------------------------------------------------
# Helper functions
# -----------------------------------------------------------------------------
info() { echo -e "${BLUE}[INFO]${NC} $1"; }
success() { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

check_command() {
    if command -v "$1" &> /dev/null; then
        success "$1 is installed"
        return 0
    else
        return 1
    fi
}

# -----------------------------------------------------------------------------
# Get script directory (works even if called from different location)
# -----------------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

info "RC Racer Development Environment Setup"
info "======================================="
echo ""

# -----------------------------------------------------------------------------
# Step 1: Check prerequisites
# -----------------------------------------------------------------------------
info "Step 1: Checking prerequisites..."
echo ""

# Check Docker
if ! check_command docker; then
    error "Docker is not installed. Please install Docker first:
    
    Ubuntu/Debian:
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo usermod -aG docker \$USER
      # Log out and back in for group changes to take effect
    
    See: https://docs.docker.com/engine/install/"
fi

# Check Docker is running
if ! docker info &> /dev/null; then
    error "Docker daemon is not running. Start it with:
      sudo systemctl start docker
    
    Or if you just added yourself to the docker group, log out and back in."
fi

# Check Docker Compose
if ! check_command docker-compose && ! docker compose version &> /dev/null; then
    error "Docker Compose is not installed. Please install it:
    
    Ubuntu/Debian (Docker Compose V2 plugin):
      sudo apt-get install docker-compose-plugin
    
    Or standalone:
      sudo curl -L \"https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)\" -o /usr/local/bin/docker-compose
      sudo chmod +x /usr/local/bin/docker-compose
    
    See: https://docs.docker.com/compose/install/"
else
    success "Docker Compose is available"
fi

echo ""

# -----------------------------------------------------------------------------
# Step 2: Configure X11 for GUI support
# -----------------------------------------------------------------------------
info "Step 2: Configuring X11 for GUI applications (Gazebo, RViz)..."
echo ""

if [ -n "$DISPLAY" ]; then
    # Allow local Docker containers to connect to X server
    xhost +local:docker 2>/dev/null || warn "Could not run xhost (may need X server running)"
    success "X11 forwarding configured (DISPLAY=$DISPLAY)"
else
    warn "No DISPLAY set. GUI applications won't work without X11."
    warn "If running over SSH, use: ssh -X user@host"
fi

echo ""

# -----------------------------------------------------------------------------
# Step 3: Create .env file
# -----------------------------------------------------------------------------
info "Step 3: Setting up docker/.env file..."
echo ""

cd "$PROJECT_ROOT"

if [ -f docker/.env ]; then
    warn "docker/.env already exists, skipping"
else
    if [ -f docker/.env.example ]; then
        cp docker/.env.example docker/.env
        success "Created docker/.env from template"
    else
        # Create default .env if no template exists
        cat > docker/.env << 'EOF'
# RC Racer Docker Environment Configuration
# Generated by setup-dev-env.sh

# Display for X11 forwarding (GUI apps)
DISPLAY=${DISPLAY:-:0}

# ROS Domain ID (change if multiple robots on same network)
ROS_DOMAIN_ID=0
EOF
        success "Created docker/.env with defaults"
    fi
fi

echo ""

# -----------------------------------------------------------------------------
# Step 4: Build development container
# -----------------------------------------------------------------------------
info "Step 4: Building development Docker container..."
info "This may take 5-10 minutes on first run..."
echo ""

cd "$PROJECT_ROOT/docker"

if docker compose build dev 2>/dev/null || docker-compose build dev; then
    success "Development container built successfully"
else
    error "Failed to build development container"
fi

echo ""

# -----------------------------------------------------------------------------
# Step 5: Verify setup
# -----------------------------------------------------------------------------
info "Step 5: Verifying setup..."
echo ""

# Start container briefly to verify
if docker compose up -d dev 2>/dev/null || docker-compose up -d dev; then
    success "Development container started"
    
    # Quick sanity check
    if docker compose exec -T dev ros2 --help &>/dev/null 2>&1 || \
       docker-compose exec -T dev ros2 --help &>/dev/null 2>&1; then
        success "ROS 2 is working inside container"
    else
        warn "Could not verify ROS 2 (container may still be starting)"
    fi
    
    # Stop the container
    docker compose stop dev 2>/dev/null || docker-compose stop dev
else
    error "Failed to start development container"
fi

echo ""

# -----------------------------------------------------------------------------
# Done!
# -----------------------------------------------------------------------------
echo -e "${GREEN}=======================================${NC}"
echo -e "${GREEN}Setup complete!${NC}"
echo -e "${GREEN}=======================================${NC}"
echo ""
info "Next steps:"
echo ""
echo "  1. Start the development container:"
echo "     cd docker && docker-compose up -d dev"
echo ""
echo "  2. Enter the container:"
echo "     docker-compose exec dev bash"
echo ""
echo "  3. Build the workspace (inside container):"
echo "     colcon build"
echo ""
echo "  4. Source and run (inside container):"
echo "     source install/setup.bash"
echo "     ros2 launch rc_racer_bringup rc_racer.launch.py"
echo ""
info "For GUI apps (Gazebo, RViz), run this on host before starting container:"
echo "     xhost +local:docker"
echo ""

